Repository oxen-io/session-android, pull requests merged in 2023-06, with the labels that each got.

#1235 Fix back button background in light themes
  app/src/main/res/values/themes.xml
Labels: bug, dev-tested

#1241 Fixed a few issues with the OpenGroupPoller
  app/src/main/java/org/thoughtcrime/securesms/groups/OpenGroupManager.kt
  libsession/src/main/java/org/session/libsession/messaging/jobs/BackgroundGroupAddJob.kt
  libsession/src/main/java/org/session/libsession/messaging/open_groups/OpenGroupApi.kt
  libsession/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/OpenGroupPoller.kt
Labels: bug

#1238 Fix broken modal styling from 1.16.8
  app/src/main/java/org/thoughtcrime/securesms/conversation/v2/DeleteOptionsBottomSheet.kt
  app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ModalUrlBottomSheet.kt
  app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/VisibleMessageView.kt
  app/src/main/java/org/thoughtcrime/securesms/conversation/v2/utilities/BaseDialog.kt
  app/src/main/java/org/thoughtcrime/securesms/home/ConversationOptionsBottomSheet.kt
  app/src/main/java/org/thoughtcrime/securesms/home/UserDetailsBottomSheet.kt
  app/src/main/res/drawable/default_dialog_background.xml
  app/src/main/res/layout/progress_dialog.xml
  app/src/main/res/layout/view_visible_message.xml
  app/src/main/res/values/styles.xml
Labels: bug

#1228 [SES-540] Add 50dp to isScrolledToBottom
  app/src/main/java/org/thoughtcrime/securesms/util/GeneralUtilities.kt
  libsession/src/main/java/org/session/libsession/utilities/ViewUtils.kt
Labels: qa-tested
